# SITE SETTINGS
title: Camtrap DP
url: "https://tdwg.github.io"
baseurl: "/camtrap-dp"

# SOCIAL PROFILES
social:
  github: tdwg/camtrap-dp

# THEME SETTINGS
theme: minima
remote_theme: tdwg/petridish
github_edit: true
logo: /assets/theme/images/tdwg-logo-short.svg

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - example/*
  - tests/*
  - "*.json"

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: pages/example
    values:
      permalink: "/example/:basename/"
      layout: example
      title: Example dataset
      toc: true
