name: Validate example against current schemas

on: push

jobs:
  validate-example-current-schema:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -r tests/requirements.txt --upgrade pip
    - name: Run validation tests
      run: |
        python tests/validate_example_current_schema.py
